M48
; DRILL file {KiCad 8.0.0} date 2024-03-18T00:14:22+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-18T00:14:22+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X1.9587Y-0.9906
X1.9587Y-1.1875
T2
X0.7835Y-0.998
X0.7835Y-1.1161
T3
X0.8268Y-0.7677
X0.9055Y-1.7584
X2.0571Y-0.7938
X2.0768Y-1.7781
M30
